### ISSUE TITLE
Put instructions for different platforms in parallel rather than series

### ISSUE THREAD

**Issue by amfarrell** [conda/conda.io#1]
The parts of the docs that have commands which are different between windows and unix should place them side-by-side and use icons to visually indicate this.

> Next you need to activate the environment so you can use it. To do that on OS X or Linux, type the following:
> 
> $ source activate dev
> ... activation output ...
> (dev) $
> On Windows, you don't have to include source:
> 
> $ activate dev
> ... activate output ...
> [dev] $

would look something like... (excuse the table-based layout)

| On OSx or Linux [logos] | On Windows [logo] |
| --- | --- |
| $source activate dev | > activate dev |
| ... activation output ... | ...activate output... |
| (dev) $ | [dev] > |

There should be a template (or perhaps just css class) for this.

**Comment by tswicegood** [comment]
This is related to #2.  I think that's a better way of handling it.

**Comment by amfarrell** [comment]
Agreed
